version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: thedutchapp:latest
    container_name: thedutchapp_backend
    env_file:
      - .local.env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - thedutchapp
    expose:
      - 8080
    # command: ["./THEDUTCHAPP"]
    command: ["go", "run", "cmd/server/main.go"]

  redis:
    image: redis:latest
    container_name: thedutchapp_redis
    ports:
      - 6379:6379
    volumes:
      - ./data/cache:/data/cache
    networks:
      - thedutchapp
    # expose:
    #   - 6379

  db:
    image: mongo:latest
    container_name: thedutchapp_db
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - thedutchapp
    # expose:
    #   - 27017

  # frontend:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   image: thedutchapp:latest
  #   container_name: thedutchapp_frontend
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - backend
  #   networks:
  #     - thedutchapp
  #   expose:
  #     - 3000

networks:
  thedutchapp:
